{-# LANGUAGE DataKinds #-}

-- |
-- Module      : Main
-- Description : Example 2 - Spatial Rotations and Rotors in Geometric Algebra
--
-- This tutorial example covers:
-- 1. Why Geometric Algebra uses Rotors instead of Matrices or Quaternions
-- 2. Generating a Rotor from a Bivector via the Exponential Map: R = exp(-B/2)
-- 3. Applying the Sandwich Transformation: v' = R * v * ~R
-- 4. Composing multiple rotations and computing rotor inverses
module Main where

import Prelude hiding ((<*>))
import Clifford

type GA3 = DenseMV Cl300 Double

main :: IO ()
main = do
  putStrLn "============================================================"
  putStrLn "  Clifford Algebra Tutorial: Example 2 - Rotations & Rotors"
  putStrLn "============================================================\n"

  -- 1. Concept: Rotations are generated by Bivectors (Planes of Rotation)
  -- In traditional vector algebra, rotations are defined around an "axis vector" (which only works in 3D).
  -- In Geometric Algebra, rotations are defined in an "oriented plane" (a Bivector), which works
  -- universally in 2D, 3D, 4D, and N dimensions!

  -- Let's rotate vector v = e1 by 90 degrees (pi/2 radians) in the e1-e2 plane towards e2.
  let v = e1 :: GA3
      theta = pi / 2
      -- Generator bivector for counter-clockwise rotation in the e12 plane:
      -- B = - (theta / 2) * e12
      bivec = scaleMV (- theta / 2) (e12 :: GA3)

  putStrLn "--- 1. Constructing a Rotor ---"
  putStrLn $ "Initial vector v = " ++ show v
  putStrLn $ "Rotation angle   = 90 degrees (pi/2 rad)"
  putStrLn $ "Rotation plane   = e12 (XY plane)"
  putStrLn ""

  -- 2. Rotor Exponential Map: R = exp(B) = cos(|B|) + (B / |B|) * sin(|B|)
  let rotor = rotorExp bivec
  putStrLn "--- 2. Rotor Value ---"
  putStrLn $ "Rotor R = exp(B) = " ++ show rotor
  putStrLn $ "Rotor norm ||R|| = " ++ show (rotorNorm rotor) ++ " (Should be exactly 1.0)"
  putStrLn ""

  -- 3. The Sandwich Transformation: v' = R * v * ~R
  -- Multiplying by R on the left and reverse(R) on the right rotates v cleanly
  -- while preserving its vector grade and norm.
  let v_rotated = sandwich rotor v

  putStrLn "--- 3. Sandwich Transformation (v' = R * v * ~R) ---"
  putStrLn $ "Rotated vector v' = " ++ show v_rotated
  putStrLn "Notice: e1 has been rotated exactly to e2!"
  putStrLn ""

  -- 4. 3D Rotation Around an Arbitrary Axis
  -- To rotate around the axis (1, 1, 1), we find the dual plane: B_axis = J(axis)
  let axis = scaleMV (1 / sqrt 3) (e1 + e2 + e3 :: GA3)
      -- The plane orthogonal to the axis is its Poincaré dual:
      planeBivec = poincareDualMV axis
      angle120 = 2 * pi / 3 -- 120 degrees
      rotor3D = rotorExp (scaleMV (- angle120 / 2) planeBivec)

  putStrLn "--- 4. 3D Rotation Around Axis (1,1,1) by 120 degrees ---"
  putStrLn $ "Axis unit vector = " ++ show axis
  putStrLn $ "Orthogonal plane = " ++ show planeBivec
  putStrLn $ "Rotor for 120°   = " ++ show rotor3D

  -- A 120 degree rotation around (1,1,1) cyclically permutes e1 -> e2 -> e3 -> e1!
  let r_e1 = sandwich rotor3D (e1 :: GA3)
      r_e2 = sandwich rotor3D (e2 :: GA3)
      r_e3 = sandwich rotor3D (e3 :: GA3)

  putStrLn $ "Rotated e1 -> " ++ show r_e1 ++ "  (Permuted to e2)"
  putStrLn $ "Rotated e2 -> " ++ show r_e2 ++ "  (Permuted to e3)"
  putStrLn $ "Rotated e3 -> " ++ show r_e3 ++ "  (Permuted to e1)"
  putStrLn ""

  -- 5. Composition of Rotations
  -- Composing rotations is as simple as multiplying their rotors: R_total = R2 * R1
  let rotorTotal = rotor3D <*> rotor
      v_doubleRot = sandwich rotorTotal v
  putStrLn "--- 5. Rotor Composition ---"
  putStrLn $ "Composed Rotor R_total = R2 * R1 = " ++ show rotorTotal
  putStrLn $ "Applying R_total to e1 = " ++ show v_doubleRot
  putStrLn ""
  putStrLn "Tutorial 2 completed successfully!"
